version: '3.8'

services:
  telegram_bot:
    build: .
    image: telegram_bot:latest
    container_name: telegram_bot
    restart: always
    environment:
      BOT_TOKEN: "${BOT_TOKEN}"
      ADMIN_CHAT_ID: "${ADMIN_CHAT_ID}"
      SCRIPT_PATH: "${SCRIPT_PATH}"
      JELLYFIN_API_KEY: "${JELLYFIN_API_KEY}"
      VIDEOS_DIR: "${VIDEOS_DIR}"
      JELLYFIN_API_URL: "${JELLYFIN_API_URL}"
      TELEGRAM_TOKEN: "${TELEGRAM_TOKEN}"
      JELLYFIN_API_MEDIA_ID: "${JELLYFIN_API_MEDIA_ID}"
    volumes:
      - ${HOME}/videos:/videos
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
