name: Build and Deploy Telegram Bot

on:
  push:
    branches:
      - main
      - actions-debug

env:
  IMAGE_NAME: telegram_bot:latest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          echo "Hellow world" | gzip > telegram_bot_image.tar.gz
      - name: Upload Docker Image as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: telegram_bot_image
          path: telegram_bot_image.tar.gz

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Docker Image
        uses: actions/download-artifact@v4
        with:
          name: telegram_bot_image
          path: ~/telegram_bot/

      - name: Check repo
        run: ls -aR

      - name: copy files to target server via scp
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "./docker-compose.yml"
          target: "~/telegram_bot/"

          
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            gzip -d telegram_bot_image.tar.gz
            docker load < telegram_bot_image.tar
            cd ~/telegram_bot
            ls -aR